# Global configuration
global:
  scrape_interval: 15s # กำหนดการดึงข้อมูลจาก target ทุก ๆ 15 วินาที

# Scrape config for PostgreSQL Exporter
scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-master-1:9187', 'postgres-master-2:9187', 'postgres-slave-1:9187', 'postgres-slave-2:9187', 'postgres-slave-3:9187', 'postgres-slave-4:9187']
    metrics_path: '/metrics'

  # Scrape config for Docker containers (ถ้าใช้ Prometheus กับ Docker)
  - job_name: 'docker'
    docker_sd_configs:
      - host: 'unix:///var/run/docker.sock'

  # Scrape config for Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
